### ISSUE TITLE
&key parameter in toLinks

### ISSUE THREAD

**Issue by mrhaw** [splittingred/tagLister#17]
Documentation example: 
[[!tolinks? &items=[[*tags]] &key=tag &target=123]]

No matter how I define "&key" I get "&key=tags" in the end of all generated links.

I.e. _ tags _ instead of _ tag _.

EDIT:
Adding &tagKey to [[toLinks]] generates that as &key value in link url. That makes sorting work! :) 
Either call it empty or using the TV-name :) Just somewhat confusing.

**Comment by tommls** [comment]
This could be explained better in the documentation. I tried many values for &key, using `` (blank), etc. and could not figure it out...&key kept popping up!!

Finally got directed here and with more experimenting figured out this is the way to call it:
[!tolinks? &items=`[[+tv.news_tags]]` &key=``&tagKey=`news_tags`&target=`7`]]`]]
two backticks after &key=
This gives the url:
http://foo/bar/news/?tag=test&key=news_tags which produce the correct subset of posts.
This is non-intuitive and someday it could be improved in the documentation or implementation.
Could &key be defaulted to blank or something more useful??
I'm sure &key has a raison d'etre but how to make it go away is not so clear. :)
Thank you, Tom
