### ISSUE TITLE
Wish: tagLister with 'parents' parameter, such like as getResourcesTag has it.

### ISSUE THREAD

**Issue by norblenn** [splittingred/tagLister#5]
Problem: tagLister gathers/counts all tags in documents. Works fine.
But I have different sections of documents (journal, magazin, blog) and I need different tags counts on different parent trees.
getResouresTag is already able to work with specified parents to display specified documents by tag. But tagLister would need also a parameter for listing/counting only these documents I want to have for exmaple from the journal tree. It is possible to use different tvs but it would be wishful that tagLister works also with children of parents to give full support to getResourcesTag.

**Comment by splittingred** [comment]
Added in latest git commit. Will be released later this week with some other fixes.
