### ISSUE TITLE
wish: tagLister with 'createdby' and 'site_keyword' parameter.

### ISSUE THREAD

**Issue by norblenn** [splittingred/tagLister#6]
problem: taglister operates usualy for a blog tags application. The functionality could be expand to authors and html site keywords.

Nearly all what's to edit for advance is this in tagLister :

  /\* get TV values */
  $c = $modx->newQuery('modTemplateVarResource');
  $c->innerJoin('modTemplateVar','TemplateVar');
  $c->innerJoin('modResource','Resource');
  $tvPk = (int)$tv;
  if (!empty($tvPk)) {
    $c->where(array('TemplateVar.id' => $tvPk));
  } else {
    $c->where(array('TemplateVar.name' => $tv));
  }

In the case of authors, one would use modWebUserProfile (createdby, fullname) instead of modTemplateVarResource.
In the case of site_keywords, it is imho modResource, modResourceKeyword.

Then you get 2 more useful applications by minimal changes.

**Comment by splittingred** [comment]
Keywords in Revo are deprecated, so no to that. modWebUserProfile is also deprecated.

I've added a &where property that you can use a JSON array to filter results in tagLister snippet:

&where=`{'CreatedBy.username':'mark123'}`

**Comment by norblenn** [comment]
Okay, but then the table site_keywords is also out of date. Is that correct because of an out-dated web concept of keywords? I don't know.

I have seen that you have also added an all-Tag. This would have been my next idea. But it is already done.

Thanks for your very fast input!

**Comment by splittingred** [comment]
Yes, the table is deprecated. Keywords in Revo should be done through TVs.
