### ISSUE TITLE
Tag filter in getResourcesTag isn't working correct

### ISSUE THREAD

**Issue by skyschub** [splittingred/tagLister#8]
Hi there!

I have a crazy problem with the tag-filter of getResourcesTag...
Let's imagine, A, B, C and D are blog-posts. 1, 2 and 3 are tags. 
A is tagged with 1, 2, 3
B is tagged with 1, 2
C is tagged with 2, 3
D is tagged with 1, 3

Okay, now click on the link of tag 1. You will see posts A, B, D. All right. If you click on another link (2 for example), you'll see nothing...

That's the problem I have right now at this site: http://modx.dennis-schubert.de/blog/

My call:
    [[!getResourcesTag?
      &element=`getResources`
      &elementClass=`modSnippet`
      &tpl=`cbBlogListItem`
      &tagKey=`cbBlogPostTags`
      &hideContainers=`1`
      &pageVarKey=`page`
      &parents=`[[+parents]]`
      &includeTVs=`1`
      &includeContent=`1`
      &tagRequestParam=`tag`
    ]]
    [[!+page.nav:notempty=`
    <div class="paging">
    <ul class="pageList">
      [[!+page.nav]]
    </ul>
    </div>
`]]

toLinks are pointing to that resource

**Comment by splittingred** [comment]
Hi, set &cache=`0` in getResourcesTag call.

**Comment by skyschub** [comment]
Hi,
still not working...

**Comment by splittingred** [comment]
Try adding &tagSearchType=`contains` to your getResourcesTag call.

**Comment by skyschub** [comment]
Nope, it's not working...

**Comment by skyschub** [comment]
Fixed: http://github.com/denschub/tagLister/commit/53df152cfe86fc059119dd2c82f15055e115b41b
