### ISSUE TITLE
Tolink URLs not HTML valid

### ISSUE THREAD

**Issue by amirfl** [splittingred/tagLister#9]
Links generated by the 'tolink' snippet include the character '&' instead of '&amp;', which causes html validation errors.

I fixed this problem on my test site by adding the following line to the 'tolink' snippet code: $itemArray['url'] = str_replace('&','&amp;',$itemArray['url']);
immediately after the line:
$itemArray['url'] = str_replace(' ','+',$itemArray['url']);

**Comment by amirfl** [comment]
The code didn't copy correctly into the message above. The str replace line I added was supposed to replace all '"&" with a "& amp;" (no space)

**Comment by skyschub** [comment]
That's fixed in my fork: http://github.com/denschub/tagLister
Already send a pull-request to splittingred, but you can already use my fork: 
http://github.com/denschub/tagLister/blob/master/core/components/taglister/elements/snippets/tolinks.snippet.php

**Comment by splittingred** [comment]
Create a system setting named 'xhtml_urls', and set it to a Yes/No and a value of 1. That will fix this.

**Comment by skyschub** [comment]
Well, this will fix the href-attribute, but not the text?! Correct me if I'm wrong.
